-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."ActivationCodeCandidates"
(
    id integer NOT NULL,
    candidate_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."ActivationCodeEmployers"
(
    id integer NOT NULL,
    emplotyers_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."ActivationCodes"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    activation_code text NOT NULL,
    is_confirmed boolean NOT NULL,
    confirm_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public."Candidates"
(
    id integer NOT NULL,
    nationality_id character varying(11) NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(10) NOT NULL,
    birthdate date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employees"
(
    id integer NOT NULL,
    first_name character varying(20) NOT NULL,
    last_name character varying(10) NOT NULL,
    title character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employers"
(
    id integer NOT NULL,
    company_name character varying(20) NOT NULL,
    web_site character varying(50) NOT NULL,
    phone_number character varying(11) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."EmployersActivationByEmployees"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employers_id integer NOT NULL,
    employees_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    confirmed_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public."Positions"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(16) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."ActivationCodeCandidates"
    ADD FOREIGN KEY (id)
    REFERENCES public."ActivationCodes" (id)
    NOT VALID;


ALTER TABLE public."ActivationCodeCandidates"
    ADD FOREIGN KEY (candidate_user_id)
    REFERENCES public."Candidates" (id)
    NOT VALID;


ALTER TABLE public."ActivationCodeEmployers"
    ADD FOREIGN KEY (id)
    REFERENCES public."ActivationCodes" (id)
    NOT VALID;


ALTER TABLE public."ActivationCodeEmployers"
    ADD FOREIGN KEY (emplotyers_user_id)
    REFERENCES public."Employers" (id)
    NOT VALID;


ALTER TABLE public."Candidates"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."EmployersActivationByEmployees"
    ADD FOREIGN KEY (employees_id)
    REFERENCES public."Employees" (id)
    NOT VALID;


ALTER TABLE public."EmployersActivationByEmployees"
    ADD FOREIGN KEY (employers_id)
    REFERENCES public."Employers" (id)
    NOT VALID;

END;